#include<iostream>
using namespace std;

int main()
{
     int marks[] = {2,4,6,8,10,12};
     cout<<"THESE ARE THE MARKS : "<<marks[0]<<endl;
     cout<<"THESE ARE THE MARKS : "<<marks[1]<<endl;
     cout<<"THESE ARE THE MARKS : "<<marks[2]<<endl;
     cout<<"THESE ARE THE MARKS : "<<marks[3]<<endl;
     cout<<"THESE ARE THE MARKS : "<<marks[4]<<endl;
     cout<<"THESE ARE THE MARKS : "<<marks[5]<<endl;
     
return 0; 
}